# SPDX-FileCopyrightText: 2022 nerdyscout <https://github.com/nerdyscout/>
#
# SPDX-License-Identifier: CC0-1.0

name: KiBot

on:
  push:
    paths:
    - "Kicad/*.kicad_sch"
    - "Kicad/*.kicad_pcb"
    - "Kicad/*.kicad_pro"
    - "**/*kibot.yml"
  pull_request:
    paths:
    - "Kicad/*.kicad_sch"
    - "Kicad/*.kicad_pcb"
    - "Kicad/*.kicad_pro"
    - "**/*kibot.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inti-cmnb/kicad9_auto:1.8.2
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: true
      - name: Get Branch Name
        if: github.event_name == 'push' && startswith(github.ref, 'refs/tags/')
        id: branch_name
        run: |
          echo "{SOURCE_TAG}=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Run Build
        run: |
          ./build.sh
      - name: Upload KiBot Output
        uses: actions/upload-artifact@v4
        if: ${{success()}}
        with:
          name: Build-Outputs
          if-no-files-found: error
          path: |
            ./docs/*
      - name: Create and Upload Release
        if: github.event_name == 'push' && startswith(github.ref, 'refs/tags/')
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./docs/*
